import {
  Banknote,
  Briefcase,
  Camera,
  CreditCard,
  DollarSign,
  Facebook,
  Github,
  Gitlab,
  Globe,
  Headphones,
  Inbox,
  Instagram,
  Linkedin,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  MoreHorizontal,
  Phone,
  PhoneCall,
  Printer,
  Send,
  Server,
  Slack,
  Smartphone,
  Twitter,
  Youtube,
} from 'lucide-react';

export const CONTACT_TYPES = [
  { type: 'phone', icon: <Phone className="size-4" />, name: 'Telefone' },
  { type: 'mobile', icon: <Smartphone className="size-4" />, name: 'Celular' },
  { type: 'email', icon: <Mail className="size-4" />, name: 'Email' },
  { type: 'address', icon: <MapPin className="size-4" />, name: 'Endereço' },
  { type: 'facebook', icon: <Facebook className="size-4" />, name: 'Facebook' },
  { type: 'instagram', icon: <Instagram className="size-4" />, name: 'Instagram' },
  { type: 'twitter', icon: <Twitter className="size-4" />, name: 'Twitter (X)' },
  { type: 'linkedin', icon: <Linkedin className="size-4" />, name: 'LinkedIn' },
  { type: 'whatsapp', icon: <MessageCircle className="size-4" />, name: 'WhatsApp' },
  { type: 'telegram', icon: <Send className="size-4" />, name: 'Telegram' },
  { type: 'youtube', icon: <Youtube className="size-4" />, name: 'YouTube' },
  { type: 'portfolio', icon: <Briefcase className="size-4" />, name: 'Portfólio' },
  { type: 'github', icon: <Github className="size-4" />, name: 'GitHub' },
  { type: 'gitlab', icon: <Gitlab className="size-4" />, name: 'GitLab' },
  { type: 'website', icon: <Globe className="size-4" />, name: 'Website' },
  { type: 'chat', icon: <MessageSquare className="size-4" />, name: 'Chat' },
  { type: 'support_phone', icon: <Headphones className="size-4" />, name: 'Telefone de Suporte' },
  { type: 'support_email', icon: <Inbox className="size-4" />, name: 'Email de Suporte' },
  { type: 'pix', icon: <Banknote className="size-4" />, name: 'Pix (Brasil)' },
  { type: 'paypal', icon: <DollarSign className="size-4" />, name: 'PayPal' },
  { type: 'credit_card', icon: <CreditCard className="size-4" />, name: 'Cartão de Crédito' },
  { type: 'fax', icon: <Printer className="size-4" />, name: 'Fax' },
  { type: 'skype', icon: <PhoneCall className="size-4" />, name: 'Skype' },
  { type: 'discord', icon: <Server className="size-4" />, name: 'Discord' },
  { type: 'snapchat', icon: <Camera className="size-4" />, name: 'Snapchat' },
  { type: 'slack', icon: <Slack className="size-4" />, name: 'Slack' },
  { type: 'others', icon: <MoreHorizontal className="size-4" />, name: 'Outros' },
];

export function getContactType(type: string) {
  return CONTACT_TYPES.find((c) => c.type === type);
}
